src/lib.rs

Cargo make its executable path available for the 3rd party extensions via `CARGO` env var.

Consult `CARGO` environment variable for `cargo` executable path

---

Cargo.toml
src/lib.rs
tests/selftest.rs

I plan to use this for https://github.com/Manishearth/rust-clippy/issues/1797.

 Include dependencies graph in the `Metadata`

---

Cargo.toml
src/dependency.rs
src/lib.rs
tests/selftest.rs

This PR does a few things:
* Use `error_chain` for errors - #11 
* Add/fix support for providing manifest path
* Run the latest rustfmt-nightly
* Make public the `req` and `kind` fields on `Dependency`
(happy to split up if that would make reviewing easier).

Use error_chain; add/fix manifest_path support; run rustfmt; expose extra `Dependency` fields

---

Cargo.toml
README.md
src/dependency.rs
src/lib.rs
tests/selftest.rs

Add a readme and usage examples. Also update the manifest path input to be an `Option<&Path>`
Should solve #16

Metdata path is now a Path; add examples of use

---

src/errors.rs

Uglier than before, but at least rustdoc picks up the comments now so we can remove the `allow`.

Use doc attributes for foreign links

---

src/lib.rs

Adds another field which is skipped by Serde to ensure that users cannot
match the struct exhaustively.
Fixes #23.

Expose `features` on Package.

---

src/dependency.rs

I would like to make the source field public to see if the dependency is local or not.

Make source field public

---

src/lib.rs

The implementation of WorkspaceMember is almost identical to PackageId in cargo.
The difference is that its deserialization is simplified and it does not use Arc internally.

Add WorkspaceMember

---

Cargo.toml
src/lib.rs
tests/selftest.rs

Since https://github.com/rust-lang/cargo/pull/5360 `cargo metadata` outputs the contents of the [optional `package.metadata` table](https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table-optional). This PR adds support for the table to this crate. Since the table can contain arbitrary content, the return type is a dynamic `serde_json::Map`.
Unresolved questions:
- Is it ok to expose types of the serde_json dependency in the public API? Or do we need to make the `serde_json` dependency public?
- The test doesn't work on stable yet. Is there a way to conditionally execute the test only on nightly and beta?

Add support for package.metadata table

---

src/lib.rs

Not sure about the API, if sounds good I can write an example before merging.

handle cargo features flags

---

Cargo.toml

On Linux and other targets, the `backtrace` crate relies upon the `cc` crate to compile `libbacktrace` – a C library. This can complicate the build.
This pull request re-exposes the `backtrace` feature of `error-chain` such that it can optionally be disabled.

Re-export backtrace feature of error-chain

---

.travis.yml

In response to https://github.com/oli-obk/cargo_metadata/pull/38#issuecomment-401598850

Add building without backtrace feature to .travis.yml

---

src/dependency.rs

The private fields in Dependency are required to perform precise dependency resolution and there is no need to keep this fields private. This change makes all the fields public and gives them a short doc, except of course __do_not_match_exhaustively.

Expose remaining fields in Dependency

---

Cargo.toml

This crate uses the `serde(transparent)` container attribute but this
attribute was only added in serde v1.0.59.

Bump serde dependency version

---

Cargo.toml

`#[serde(transparent)]` wasn't implemented in `serde_derive` until [v1.0.59](https://github.com/serde-rs/serde/releases/tag/v1.0.59), but it's used here:
https://github.com/oli-obk/cargo_metadata/blob/313cc0b85d4cb1b6ad6fc95004450f88740e02c9/src/lib.rs#L236
(This actually caused a build failure for me in an unrelated crate since I hadn't run `cargo update` in forever :man_shrugging:)

Bump serde_derive version

---

src/lib.rs

The error seems to be extremely rare, for some reason.
Conditions:
- rustc 0.24.0 (Stable)
- Linux (travis build, so I don't know which one exactly)
- cargo_metadata version 0.6.2
- Project is nested:
-- Parent project isn't published
-- Child project is published
-- cargo_metadata called from tests in the parent project
-- Parent project isn't a workspace
-- Parent project `Cargo.toml` is minimal; no `categories` entry.
- (Specific build log: https://travis-ci.org/budziq/rust-skeptic/jobs/462642234 from budziq/rust-skeptic#91)

Fix error when no categories are provided

---

Cargo.toml
src/errors.rs

error-chain uses deprecated method and there's no update yet.
docopt is now stable.

Update dep, silence deprecation

---

src/lib.rs

Current Cargo has more data. The `root` is especially important for working with workspaces.

Add more fields

---

src/lib.rs
tests/selftest.rs

closes #51
cc https://github.com/rust-lang/cargo/pull/6511

Unstringlytypify

---

src/lib.rs

Instead of wrapping them in '[' and ']'.
This change is untested!

Correctly pass comma-separate features to cargo

---

.travis.yml
src/lib.rs

Now that 1.33.0 is out and `trim_left_matches()` deprecation has reached stable channel it may be a good time to update the example/doc test
Fix #65

Replace trim_left_matches with trim_start_matches

---

src/lib.rs

Well, I need it for a private project right now and I guess it was private by mistake to begin with.

Make Package field source public

---

src/lib.rs
tests/test_samples.rs

Change MetadataCommand::current_dir so it has an effect.
Fixes #82. This is a work around for the issue #82.

Fix support for current_dir.

---

Cargo.toml
src/errors.rs
src/lib.rs

We don't actually use any of failure's features anyway, and having less public dependencies is good for a library.
Here's what we lose from this:
```
λ cargo update
Updating crates.io index
Removing backtrace v0.3.33
Removing backtrace-sys v0.1.31
Removing cc v1.0.38
Removing cfg-if v0.1.9
Removing failure v0.1.5
Removing failure_derive v0.1.5
Removing rustc-demangle v0.1.15
Removing synstructure v0.10.2
```
Note that technically this is a breaking change

replace failure with just manually implementing an error

---

src/lib.rs

To be able to fully use `parse_messages`, pub access is required for diagnostic types. Currently, it's not possible to match on `Diagnostic`'s `level` field because `DiagnosticLevel` is private.

make diagnostic types pub

---

src/lib.rs
tests/test_samples.rs

Since the `Package::readme` field is public this would be a breaking change.
However, the ~aaec6f1~ 5448745  by itself should not break anything, while providing handy accessors, even without the updating (~3706bb2~ 66c3296) `Package::readme` field.

package.readme should be Option<PathBuf> rather than Option<String>

---

src/dependency.rs
src/lib.rs

AFAICT `Source` and `Platform` are the only 2 public types that don't publicly expose their inner representation, which makes them inconsistent with the rest of the types exposed by cargo_metadata. This change makes them both use the same pattern as `PackageId` so that they can be inspected without doing a copy via Display first, but allows the type to evolve in the future with a more type safe interface (such as #94) in the future without necessarily breaking backwards compatibility.
Resolves: #95

Make Source's and Platform's inner String pub

---

src/lib.rs

Thanks a lot for this crate! Here is a typo that I spotted while reading the documentation. [codepsell](https://github.com/codespell-project/codespell) did not find more typos.

Typo fixed

---

src/errors.rs

Fix the following warning:
warning: trait objects without an explicit `dyn` are deprecated
--> src/errors.rs:96:34
|
96 |     fn source(&self) -> Option<&(::std::error::Error + 'static)> {
|                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn ::std::error::Error + 'static`
|
= note: `#[warn(bare_trait_objects)]` on by default

src/errors: fix compiler warning

---

src/lib.rs
tests/test_samples.rs

According to the documentation Package.license_file() returns the full path
to the license file, if present in metadata. However, in reality it
returned the name of the license file concatenated to the full path of the
Cargo.toml file.

src/lib: fix license_file()

---

Cargo.toml
src/lib.rs

Listing three separate ways to parse command-line arguments in Rust is
not really helpful. If you are using `cargo metadata`, it's quite
likely that you are already a somewhat of an expert in Rust, and it's
rather unlikely that you literally want to just wrap it as is.
OTOH, the fact that most of the crate-level docs is occupied by
argument parsing makes finding the relevant info more difficult.

Remove distracting info from documentation

---

src/lib.rs

Hi.
I have an application where I wanted to save the output from cargo metadata, which cargo_metadata produces internally.
The Metadata struct contains two useful pieces of functionality: the Command builder and the parser (which is built with serde of course).  I think the best approach is simply to expose these two pieces so they can be used separately.  The split is still not complete because `--format-version` would need special handling, but it's good enough for my purposes.
I have tested this with `cargo check` (my tests were run with this rebased on top of my out-of-tree tests chdir MR branch).  There are no separate new tests because both the new functions `cargo_command` and `parse` are called by `exec`, so already tested.  `parse` is trivial in any case and provided partly in …

Split command parse

---

src/lib.rs

* Potentially reduce the number of clones required.
* Make the `exec` method `&self`.
(The second one breaks API compat I believe, hope that's ok!)

Some improvements to MetadataCommand

---

src/messages.rs

As per the the cargo documentation which [says](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-cfg):
> single identifier, or any arbitrary key/value pair [...] key should be a Rust identifier, the value should be a string
`String` should cover this.
This is a breaking change.
ref rust-analyzer/rust-analyzer#4296

 Correct BuildScript.cfgs to be String rather than PathBuf

---

src/lib.rs
src/messages.rs

Added in https://github.com/rust-lang/cargo/pull/8069

Add BuildFinished message.

---

Cargo.toml
src/lib.rs
src/messages.rs
tests/test_samples.rs

would appreciate a release with this one!

Robust message parsing

---

Cargo.toml
src/lib.rs

This will allow us to bump semver in clippy, it currently conflicts because cargo-metadata still requires 0.9 instead of 0.10.

deps: bump semver from 0.9 to 0.10

---

src/lib.rs
tests/test_samples.rs

The PR addresses #79 while remaining API compatible. `MetadataCommand` now supports multiple calls to `features()`. We can now express
```bash
cargo metadata --no-default-features --features feat1
```
as
```rust
MetadataCommand::new()
.features(CargoOpt::NoDefaultFeatures)
.features(CargoOpt::SomeFeatures(vec!["feat1".into()])
// ...
```
See the tests for a demonstration.
Note that this is API compatible, but not behaviorally the same. This might break any user who relies on subsequent calls to `features()` that override previous calls to `features()`.

Advanced feature configuration

---

Cargo.toml

as older versions can't compile cargo_metadata because of https://github.com/serde-rs/serde/issues/1804

bump serde dependency to 1.0.107

---

src/lib.rs
tests/test_samples.rs

Added in https://github.com/rust-lang/cargo/pull/8478
I'm a little uncomfortable with the "always true" logic for older versions, but based on the conversation at https://github.com/oli-obk/cargo_metadata/pull/88#discussion_r336556684 I think this is what you would prefer.
Closes #114.

Add `test` field to Target.

---

src/lib.rs

Add the Metadata.root_package convenience method.

---

src/lib.rs
tests/all/Cargo.toml
tests/test_samples.rs

This adds support for the new "metadata" field found at the workspace level.
Also, this eliminates the workspace and project metadata fields from being serialized if they are null.

Add workspace metadata field.

---

src/errors.rs

- Trim ending newlines from cargo_metadata output
- Use lowercase errors, as per https://rust-lang.github.io/api-guidelines/interoperability.html#error-types-are-meaningful-and-well-behaved-c-good-err.
- Rearrange `CargoMetadata` not to start with `error`, which looks funny
when prefixed with `ERROR` the way `log` and `tracing` show it.
Closes https://github.com/oli-obk/cargo_metadata/issues/138.

Improve error messages

---

Cargo.toml

This fixes the following build error:
```
error[E0658]: non-builtin inner attributes are unstable (see issue #54726)
--> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/semver-parser-0.10.1/src/generated.rs:4:1
|
4 | #![rustfmt::skip]
| ^^^^^^^^^^^^^^^^^
```

Pin a version of semver-parser to keep compatibility with 1.32

---

Cargo.toml
src/dependency.rs

Closes https://github.com/oli-obk/cargo_metadata/issues/94.
I'm not sure how to test this - maybe since it's in a different crate it doesn't need tests? The existing tests at least make sure that it parses successfully, though.

Use `cargo_platform` instead of an opaque string

---

src/lib.rs

It can't ever fail.
Found while working on https://github.com/oli-obk/cargo_metadata/issues/81, I hope to have a fix for that soon.

Don't return a Result from `cargo_command`

---

src/errors.rs

Before: `error: No such file or directory (os error 2)`
After: ``error: failed to start `cargo metadata`: No such file or directory (os error 2)``
Closes https://github.com/oli-obk/cargo_metadata/issues/81 (it's not a custom error but it should be much more clear what's going on).
I'm not sure the difference between 'failed to create the process' and 'the process ran but exited with an error' is very clear. I don't know how to improve it, though.

Give a better message on IO errors

---

src/lib.rs

Otherwise, errors and warnings will be completely hidden.
This would have avoided https://github.com/deadlinks/cargo-deadlinks/issues/113.

Recommend --message-format=json-rendered-diagnostics

---

.gitignore
src/dependency.rs

We ran into this in `cargo-geiger` when migrating from `cargo::core` to `cargo_metadata`, where we used the DependencyKind enum as keys in a `HashMap`.
We have implemented a temporary work around, using a privately declared enum, but it would be great to be able to use this enum.
Thanks,
Josh

NOISSUE - Derive `Eq` and `Hash` traits for `DependencyKind`

---

Cargo.toml

semver-parser 0.10.2 is compatible with older rust versions.

Unpin semver-parser

---

.travis.yml
Cargo.toml
src/dependency.rs
src/lib.rs
src/messages.rs
tests/test_samples.rs

[`camino`] is a library I just released which provides thin wrappers over Path
and PathBuf which guarantee that their contents are UTF-8. The readme at
https://crates.io/crates/camino explains the advantages of using this
library.
Given that:
* `cargo` only supports UTF-8 paths for cross-platform compatibility
reasons
* `serde` only supports UTF-8 paths: https://docs.serde.rs/src/serde/ser/impls.rs.html#776-778
* JSON, as a format, only supports UTF-8 strings
all valid metadata instances are already forced to be UTF-8. This means
that `cargo_metadata` can switch over to using UTF-8 paths without any
loss of functionality.
What do you think?
[`camino`]: https://crates.io/crates/camino

[RFC] use camino::Utf8PathBuf for returned paths

---

src/diagnostic.rs

I don't know how this should be added correctly, so I just did it a way that works for me. It was also unclear how to add tests for it.
To generate a message with this level, an empty project with main.rs like this will do
fn test(a: i32) {
println!("Got {}", a);
}
fn main() {
test("hello");
}
The message in question is
For more information about this error, try `rustc --explain E0308`.
The json output is
{"reason":"compiler-message","package_id":"repro 0.1.0 (path+file:///home/boh/repro)","target":{"kind":["bin"],"crate_types":["bin"],"name":"repro","src_path":"/home/boh/repro/src/main.rs","edition":"2018","doc":true,"doctest":false,"test":true},"message":{"rendered":"For more information about this error, try `rustc --explain E0308`.\n","children":[],"code":null,"level":"failure-note","m …

Added support for the diagnistic level failure-note

---

src/dependency.rs
tests/test_samples.rs

This reuses the Serialize impl for consistency.
Fixes https://github.com/oli-obk/cargo_metadata/issues/156

impl Display for DependencyKind

---

tests/all/Cargo.toml
tests/test_samples.rs

This fixes some tests due to some recent changes in cargo:
* `dylib` and `cdylib` can't be set at the same time: https://github.com/rust-lang/cargo/pull/10243
* optional dependencies now appear as features in the features table: https://github.com/rust-lang/cargo/pull/10269

Fix tests due to changes since 1.60

---

src/lib.rs
tests/selftest.rs

Inspired by [this](https://github.com/killercup/cargo-edit/blob/8a14de08c204e77374187f2d9348bae497803909/src/metadata.rs#L26) cargo-edit method, I thought it might be nice to have this functionality in this crate, directly.

add Metadata::workspace_packages method

---

src/lib.rs

This makes it easier for the user of cargo_metadata to manipulate the
Version without having to add semver to their dependencies.

Re-export semver::Prerelease and BuildMetadata

---

src/lib.rs

Previously, `Edition` was a plain enum. This means that once the 2024
edition is available, cargo_metadata would no longer be able to parse
it.
Instead, define `Edition` as a newtype over strings, to enable future
expandability while still being able to conveniently compare against
currently-known editions.
Fixes #182.

define Edition using a newtype over strings

---

.gitignore

It is often useful to put temporary file in `tmp/` and `temp/` directories. This pull request simply adds those directories to the .gitignore file so that they aren't accidentally commited to the repo

Ignore temp directories

---

src/lib.rs

As mentioned in #183 this makes the Edition an enum again but also future proofs it by adding an `Unknown` variant

Made edition an enum again

---

src/lib.rs
tests/test_samples.rs

Fix `Package::readme()` to return correct path

---

src/lib.rs

In skeptic, I'd like to be able to pass an `Edition` in a command-line flag to rustc.
Could potentially also add a `fmt::Display` impl.

Add `Edition::as_str()` method

---

src/lib.rs

These mirror the methods available in `cargo` itself: https://docs.rs/cargo/0.64.0/cargo/core/manifest/struct.Target.html#method.is_lib

Add `is_lib`, `is_bin` etc to `Target`

---

src/lib.rs

Allow `MetadataCommand` to inherit stderr from parent

---

src/messages.rs

Add `#[serde(default)]` to `Artifact::manifest_path`

---

.github/workflows/release.yml

Add a [manually-triggered workflow](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow) for releasing a new version of `cargo_metadata`, complete with build caching, tagging, and cargo-semver-checks.
This uses a "bare" tag format like `0.15.2`, following the example of the most recent tags in the project. Some of the older tags use a `v`-prefixed tag name like `v0.13.0`; if that's a preferable format then I'd be happy to switch it.
It's also possible to make a workflow that is automatically triggered once `Cargo.toml` is updated with a new version on the `main` branch. This is how I generally configure my projects (e.g. [that's how `cargo-semver-checks` releases](https://github.com/obi1kenobi/cargo-semver-checks/blob/main/.github/workflows/release.yml)), …

Release via GitHub Actions, with semver-checking and git tag.

---

README.md

Travis is dead since 2021: https://github.com/oli-obk/cargo_metadata/commit/fa404d73f248b02cf7c79c27e0bd99644360e57b

Replace Travis badge with GitHub Actions in readme

---

src/lib.rs

cc @oli-obk .. Thanks for the awesome crate!
The builder types were not exported out of the crate, which means users cannot construct new messages.
This PR exposes the builder types, hidden behind the feature flag.
Any feedback is appreciated.

export builder types to public API

---

Cargo.toml
src/lib.rs

Version 0.12.0 of the `derive_builder` crate introduces only a small breaking change which does not affect this crate.
I have also bumped the MSRV of `cargo_metadata` to 1.56.0 - I tried compiling this crate with the currently set 1.42.0, which fails (even before bumping derive_builder to v0.12) because some of this crate's dependencies have moved to the Rust 2021 edition (which was stabilized in Rust 1.56.0).

bump derive_builder dependency to v0.12

---

src/lib.rs

doc: state inner repr of `Source` is opaque

---

src/lib.rs
src/messages.rs
tests/test_samples.rs

There was an unanticipated change in 1.71 that added stringly-typed debuginfo in the profile struct. After discussing with the cargo team, we have decided to keep this change even though it has caused breakage. Fortunately this only affects projects which have opted-in to the string-based variants. 
There isn't a clear alternative for how to represent this information (they can't be accurately mapped to numbers), and we don't have a way to version this JSON output (which would also be a breaking change if we changed the version). We currently don't have a good story for how to manage JSON compatibility of the compiler messages, which is something we should probably figure out at some time.
I decided to go ahead and map the values to their semantic meaning, with an escape hatch for unknown …

Update debuginfo for change in 1.71

---

src/lib.rs

I needed it in https://github.com/CycloneDX/cyclonedx-rust-cargo/pull/554 but I ended up hand-rolling it

Add `Target.is_proc_macro()` function

---

src/lib.rs

I only realized that far more values than documented are possible in the `Target.kind` fields after my code broke for end users.
This brings the crate doc commends in line with [the official documentation on `cargo metadata`](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html).
The docs for `kind` are based on both the `cargo metadata` documentation and my experiments, while the docs for `crate_types` are based on documentation alone.

Fix docs for `Target.kind` and `Target.crate_types`

---

CHANGELOG.md
src/lib.rs
tests/selftest.rs
tests/test_samples.rs

Converting Target kind and crate_types to enum representation, along with an Unknown(String) as a fallback.
This is in response to the following issue: https://github.com/oli-obk/cargo_metadata/issues/239

Converting Target kind and crate_types to enum representation

---

src/lib.rs

While iterating through dependency packages, I find myself needing to look up dependency nodes recursively through the graph, in the same way that I need `Package` information for its `PackageId` via the already-existing `ops::Index` implementation on `Metadata`.  This is simpler if the indexing operation is also available on a `Resolve`d graph.

Implement `ops::Index` with `PackageId` for `Resolve` graph

---

src/lib.rs

Convert `Target::is_kind` pub and use macro to support all kind

---

src/lib.rs

I was surprised to see that `Metadata` didn't implement `Eq`, when most of its members already do.
This PR aims to fill these last remaining blind spots.

Derive `PartialEq` and `Eq` traits for `Metadata`

---

src/lib.rs

Changes:
- Ensure optional field are not required using `builder(default)`. The documentation implies this can be put on the struct instead of each field but in practice that requires `Package: Default` which we probally don't want.
- Add a `PackageBuilder::new` method which takes all required fields and returns a `PackageBuilder`. This is optional as `PackageBuilder::default` does work it provides some extra safety to downstream users as they will get compile errors if required fields are added in a future major.
One implication of adding `PackageBuilder::new` is that adding a new required field will requiring modifying the `new` method which is a breaking change requiring a major version. Technically in the old setup you could be add a non-required field without breaking the compliation …

Improve `PackageBuilder`

---

src/dependency.rs
src/lib.rs

This PR is sort of a follow-up of https://github.com/oli-obk/cargo_metadata/pull/267, aiming to fill the very last remaining blind spot: `Hash`.
(Motivation: I found myself in need of `Hash` for `Metadata` and its members as I otherwise couldn't use them as `HashMap`/`HashSet` keys, which is crucial for my use case.)

Derive `Hash` traits for `Metadata` and its transitive members

---

CHANGELOG.md
Cargo.toml

@oli-obk I've gone through the latest commits and added any missing changes to the `CHANGELOG.md` file and bumped the version from `0.18.1` to `0.19.0` due to the included bump of MSRV.
Lemme know if I missed anything here for a release.

Prepare release of v0.19.0

---

src/lib.rs

I'd like to use the string representations in a few places (particularly to avoid exposing cargo-metadata types as a public dependency). Add `FromStr` and `Display` impls.
Closes #275.

add FromStr and Display impls for TargetKind and CrateType

---

src/lib.rs

Set a default value when Metadata is deserialized with WorkspaceDefaultMembers skipped in serialization.

fix(Metadata): add `#[serde(default)]` on workspace_default_members field

---

Cargo.toml

`serde_json::Value` started implementing `Hash` starting from v1.0.118

build: fix -Zminimal-versions

---

src/lib.rs
tests/selftest.rs
tests/test_samples.rs

This method checks whether the called `cargo-metadata` supports reading the workspace default members, which is false for versions of Cargo prior to 1.71
Alternatively, I could:
- add an Option variant method like `workspace_default_packages` directly on `Metadata`: `pub fn workspace_default_packages(&self) -> Option<Vec<&Package>>`, or
- reverse the name from `is_available` to `is_missing` (which would also allow the removal of the `doc(hidden)` function `workspace_default_members_is_missing`).
fixes #254

Add method to check whether WorkspaceDefaultMembers has a value

---

src/lib.rs

This PR renames the `Edition::_E2024` variant to `Edition::E2024` and exposes it in the documentation given its stabilization in Rust 1.85.0.

feat: `2024` edition stabilized

---

CHANGELOG.md
src/dependency.rs
tests/test_samples.rs

They have the exact same representation (i.e. bare string) in the JSON output of `cargo metadata`, so might as well use the same type in `Metadata`.

Make `Dependency`'s `source` member the same type as `Package`'s `source` member: `Option<Source>`
