tests/selftest.rs

Fix tests on nightly

---

src/lib.rs

add `workspace_members` field to solve #3

add `workspace_members` field to solve #3

---

src/errors.rs
src/lib.rs

Needed to allow error chaining to work properly.

Export ErrorKind

---

src/lib.rs

Needed to fix https://github.com/rust-lang-nursery/rustfmt/issues/2488.

Add workspace_root field

---

src/lib.rs

While I'm here, also adds a period for the sentence.

fix doc typo: Witch to Which

---

src/lib.rs
tests/selftest.rs

Resolves #70.
Doesn't include any tests because I couldn't think of a good way to test it.  If you have any suggestions I'll happily add some.

Add more customizable options to MetadataCommand.

---

src/messages.rs

see https://github.com/rust-lang/cargo/blob/0e35bd8af0ec72d3225c4819b330b94628f0e9d0/src/cargo/util/machine_message.rs#L40

add executable to artifact

---

Cargo.toml
src/errors.rs
src/lib.rs
tests/selftest.rs

Fix #67
Now Error is `'statis + Send + Sync` before it
was not `Sync` which could cause problems.

Use failure based error instead of error_chain.

---

tests/test_samples.rs

No need to keep this test around.

Fold the links test into all_the_fields.

---

src/dependency.rs
src/lib.rs
tests/test_samples.rs

Added in https://github.com/rust-lang/cargo/pull/7132.

Add resolver dependency kinds.

---

src/messages.rs

Added in https://github.com/rust-lang/cargo/pull/7622.

Add BuildScript::out_dir

---

tests/selftest.rs
tests/test_samples.rs

This fixes #119 by removing broken test cases.

Remove broken tests.

---

Cargo.toml
src/dependency.rs
src/diagnostic.rs
src/lib.rs
src/messages.rs

Fix duplicate import by simplifying imports

---

Cargo.toml

Signed-off-by: koushiro <koushiro.cqx@gmail.com>

Update semver to v0.11.0

---

src/lib.rs
tests/all/Cargo.toml
tests/test_samples.rs

Closes https://github.com/oli-obk/cargo_metadata/issues/140

Add `documentation` and `homepage` to `Package`

---

README.md

Remove outdated from readme

---

.github/workflows/main.yml
Cargo.toml
src/lib.rs
tests/test_samples.rs

Small changes to improve the overall crate quality

---

CHANGELOG.md

Adds a simple changelog file to keep track of the various changes.

Added Changelog file

---

Cargo.toml
src/errors.rs

Implement Error using thiserror crate.

---

Cargo.toml

Update `cargo-util-schemas` to version 0.8.1
